version: '3'
services:
  bot:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WECHATY_PUPPET=wechaty-puppet-wechat
      - WECHATY_LOG=verbose
    restart: unless-stopped
