version: '3'
services:
  bot:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WECHATY_PUPPET=wechaty-puppet-wechat
      - WECHATY_LOG=verbose
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - TZ=Asia/Shanghai
    restart: unless-stopped
