version: '3'
services:
  bot:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/python_bot/__pycache__
    environment:
      - WECHATY_PUPPET=wechaty-puppet-wechat
      - WECHATY_LOG=verbose
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - WECHATY_PUPPET_SERVICE_NO_RETRY_MAX=true
      - WECHATY_PUPPET_SERVICE_TIMEOUT=300000
      - WECHATY_PUPPET_SERVICE_RETRY_DELAY=30000
      - PUPPETEER_TIMEOUT=300000
      - PUPPETEER_NAVIGATION_TIMEOUT=300000
      - WECHATY_PUPPET_WECHAT_PUPPETEER_STEALTHLESS=true
      - WECHATY_PUPPET_WECHAT_PUPPETEER_HEAD=false
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    network_mode: "host"
